server:
  appVersion: api/v1
  localLink: http://localhost:8004/
  port: 8004

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/beauty
    username: postgres
    password: kimani89
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl_auto: update
    show_sql: true
    database: postgresql

eureka:
  instance:
    host: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8000/eureka/