server:
  port: 8001
  appVersion: /api/v1
  localLink: http://localhost:${server.port}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discover:
            locator:
              enabled: true
          routes:
            - id: product-service
              uri: lb:http://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/product/**

            - id: salon-service
              uri: lb:http://SALON-SERVICE
              predicates:
                  - Path=/api/v1/salon/**
eureka:
  instance:
    host: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
